/* Shared SystemFit PC game data.
 * Lists/profiles are preserved exactly from their current tool sources.
 * Do not change workload/profile values without explicit approval.
 */
const SFP_GAME_DATA = {
  "bottleneckCatalog": [
    "Counter-Strike 2",
    "VALORANT",
    "Fortnite",
    "Apex Legends",
    "Call of Duty: Warzone",
    "PUBG: BATTLEGROUNDS",
    "Overwatch 2",
    "Rainbow Six Siege",
    "Rocket League",
    "Team Fortress 2",
    "League of Legends",
    "Dota 2",
    "The Finals",
    "Marvel Rivals",
    "Destiny 2",
    "Halo Infinite",
    "Halo: The Master Chief Collection",
    "Battlefield 2042",
    "Battlefield V",
    "Battlefield 1",
    "Battlefield 6",
    "Warframe",
    "War Thunder",
    "World of Tanks",
    "World of Warships",
    "Enlisted",
    "Delta Force",
    "Arena Breakout: Infinite",
    "Escape from Tarkov",
    "Hunt: Showdown 1896",
    "Squad",
    "Insurgency: Sandstorm",
    "Hell Let Loose",
    "Ready or Not",
    "Arma 3",
    "Arma Reforger",
    "DayZ",
    "Rust",
    "SCUM",
    "V Rising",
    "Deadlock",
    "Garry's Mod",
    "FiveM",
    "Grand Theft Auto Online",
    "Red Dead Online",
    "For Honor",
    "Chivalry 2",
    "Mordhau",
    "BattleBit Remastered",
    "Naraka: Bladepoint",
    "Brawlhalla",
    "Street Fighter 6",
    "Tekken 8",
    "Mortal Kombat 1",
    "Mortal Kombat 11",
    "Guilty Gear -Strive-",
    "Dragon Ball FighterZ",
    "The King of Fighters XV",
    "Street Fighter V",
    "Tekken 7",
    "Smite 2",
    "SMITE",
    "Heroes of the Storm",
    "StarCraft II",
    "StarCraft Remastered",
    "Warcraft III: Reforged",
    "Age of Empires IV",
    "Age of Empires II: Definitive Edition",
    "Age of Mythology: Retold",
    "Company of Heroes 3",
    "Company of Heroes 2",
    "Total War: WARHAMMER III",
    "Total War: WARHAMMER II",
    "Total War: Three Kingdoms",
    "Total War: Rome II",
    "Total War: Shogun 2",
    "Cyberpunk 2077",
    "Hogwarts Legacy",
    "Starfield",
    "Alan Wake 2",
    "Black Myth: Wukong",
    "Monster Hunter Wilds",
    "Elden Ring",
    "Baldur's Gate 3",
    "Helldivers 2",
    "Grand Theft Auto V",
    "Grand Theft Auto IV",
    "Red Dead Redemption 2",
    "Red Dead Redemption",
    "The Witcher 3: Wild Hunt",
    "The Witcher 2: Assassins of Kings",
    "The Witcher",
    "Kingdom Come: Deliverance II",
    "Kingdom Come: Deliverance",
    "Assassin's Creed Shadows",
    "Assassin's Creed Mirage",
    "Assassin's Creed Valhalla",
    "Assassin's Creed Odyssey",
    "Assassin's Creed Origins",
    "Assassin's Creed Unity",
    "Assassin's Creed Syndicate",
    "Assassin's Creed IV Black Flag",
    "Assassin's Creed III",
    "Assassin's Creed II",
    "Assassin's Creed Brotherhood",
    "Assassin's Creed Revelations",
    "Far Cry 6",
    "Far Cry 5",
    "Far Cry New Dawn",
    "Far Cry 4",
    "Far Cry 3",
    "Far Cry 2",
    "Far Cry",
    "Watch Dogs: Legion",
    "Watch Dogs 2",
    "Watch Dogs",
    "Avatar: Frontiers of Pandora",
    "Star Wars Outlaws",
    "Star Wars Jedi: Survivor",
    "Star Wars Jedi: Fallen Order",
    "Star Wars Battlefront II",
    "Star Wars Battlefront",
    "Star Wars Squadrons",
    "Indiana Jones and the Great Circle",
    "DOOM: The Dark Ages",
    "DOOM Eternal",
    "DOOM",
    "DOOM 3",
    "Wolfenstein: The New Order",
    "Wolfenstein II: The New Colossus",
    "Wolfenstein: Youngblood",
    "Prey",
    "Deathloop",
    "Dishonored 2",
    "Dishonored",
    "Death Stranding Director's Cut",
    "Death Stranding",
    "Control",
    "Control Ultimate Edition",
    "Quantum Break",
    "Alan Wake Remastered",
    "Alan Wake",
    "Resident Evil 4",
    "Resident Evil Village",
    "Resident Evil 3",
    "Resident Evil 2",
    "Resident Evil 7",
    "Resident Evil 6",
    "Resident Evil 5",
    "Resident Evil Revelations 2",
    "Resident Evil Revelations",
    "Devil May Cry 5",
    "Devil May Cry 4 Special Edition",
    "Devil May Cry 3 Special Edition",
    "Metal Gear Solid V: The Phantom Pain",
    "Metal Gear Solid V: Ground Zeroes",
    "Metal Gear Rising: Revengeance",
    "Nioh 2",
    "Nioh",
    "Lies of P",
    "Lords of the Fallen",
    "Wo Long: Fallen Dynasty",
    "Sekiro: Shadows Die Twice",
    "Dark Souls III",
    "Dark Souls II",
    "Dark Souls Remastered",
    "Dark Souls",
    "Armored Core VI: Fires of Rubicon",
    "Remnant II",
    "Remnant: From the Ashes",
    "The Outer Worlds",
    "Fallout 4",
    "Fallout: New Vegas",
    "Fallout 3",
    "Fallout 76",
    "The Elder Scrolls V: Skyrim Special Edition",
    "The Elder Scrolls V: Skyrim",
    "The Elder Scrolls IV: Oblivion Remastered",
    "The Elder Scrolls IV: Oblivion",
    "The Elder Scrolls Online",
    "Mass Effect Legendary Edition",
    "Mass Effect 3",
    "Mass Effect 2",
    "Mass Effect",
    "Dragon Age: The Veilguard",
    "Dragon Age: Inquisition",
    "Dragon Age II",
    "Dragon Age: Origins",
    "BioShock Infinite",
    "BioShock 2 Remastered",
    "BioShock Remastered",
    "BioShock",
    "Borderlands 3",
    "Borderlands 2",
    "Borderlands",
    "Tiny Tina's Wonderlands",
    "Tom Clancy's Ghost Recon Breakpoint",
    "Tom Clancy's Ghost Recon Wildlands",
    "Tom Clancy's The Division 2",
    "Tom Clancy's The Division",
    "Sleeping Dogs: Definitive Edition",
    "Mafia: Definitive Edition",
    "Mafia II Definitive Edition",
    "Mafia III",
    "Mafia",
    "L.A. Noire",
    "Max Payne 3",
    "Max Payne 2",
    "Max Payne",
    "Just Cause 4",
    "Just Cause 3",
    "Just Cause 2",
    "Just Cause",
    "Saints Row",
    "Saints Row IV",
    "Saints Row: The Third Remastered",
    "Saints Row 2",
    "Middle-earth: Shadow of War",
    "Middle-earth: Shadow of Mordor",
    "Mad Max",
    "Batman: Arkham Knight",
    "Batman: Arkham City",
    "Batman: Arkham Origins",
    "Batman: Arkham Asylum",
    "Marvel's Spider-Man Remastered",
    "Marvel's Spider-Man: Miles Morales",
    "Marvel's Spider-Man 2",
    "Ratchet & Clank: Rift Apart",
    "Horizon Forbidden West Complete Edition",
    "Horizon Zero Dawn Complete Edition",
    "Days Gone",
    "Ghost of Tsushima DIRECTOR'S CUT",
    "God of War",
    "God of War Ragnarök",
    "Uncharted: Legacy of Thieves Collection",
    "The Last of Us Part I",
    "The Last of Us Part II Remastered",
    "Returnal",
    "Sackboy: A Big Adventure",
    "Kena: Bridge of Spirits",
    "A Plague Tale: Requiem",
    "A Plague Tale: Innocence",
    "Metro Exodus Enhanced Edition",
    "Metro Exodus",
    "Metro: Last Light Redux",
    "Metro 2033 Redux",
    "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    "S.T.A.L.K.E.R.: Call of Pripyat",
    "S.T.A.L.K.E.R.: Shadow of Chernobyl",
    "S.T.A.L.K.E.R.: Clear Sky",
    "Crysis Remastered",
    "Crysis 3 Remastered",
    "Crysis 2 Remastered",
    "Crysis 2",
    "Crysis",
    "Ryse: Son of Rome",
    "Darksiders III",
    "Darksiders II Deathinitive Edition",
    "Darksiders Warmastered Edition",
    "Final Fantasy XIV Online",
    "Final Fantasy XVI",
    "Final Fantasy VII Rebirth",
    "Final Fantasy VII Remake Intergrade",
    "Final Fantasy XV",
    "Final Fantasy XIII",
    "Final Fantasy XII The Zodiac Age",
    "Final Fantasy X/X-2 HD Remaster",
    "Final Fantasy IX",
    "Final Fantasy VIII Remastered",
    "Final Fantasy VII",
    "Final Fantasy VI",
    "Final Fantasy V",
    "Final Fantasy IV",
    "Final Fantasy III",
    "Final Fantasy II",
    "Final Fantasy",
    "Path of Exile 2",
    "Path of Exile",
    "Diablo IV",
    "Diablo III",
    "Diablo II: Resurrected",
    "Diablo II",
    "Diablo",
    "World of Warcraft",
    "World of Warcraft Classic",
    "Guild Wars 2",
    "Guild Wars",
    "Lost Ark",
    "Black Desert",
    "New World: Aeternum",
    "New World",
    "Throne and Liberty",
    "RuneScape",
    "Old School RuneScape",
    "MapleStory",
    "Albion Online",
    "EVE Online",
    "Star Wars: The Old Republic",
    "Lord of the Rings Online",
    "Neverwinter",
    "Blade & Soul",
    "Vindictus",
    "Tree of Savior",
    "MIR4",
    "Torchlight II",
    "Torchlight III",
    "Grim Dawn",
    "Last Epoch",
    "Titan Quest Anniversary Edition",
    "Wolcen: Lords of Mayhem",
    "Warhammer 40,000: Rogue Trader",
    "Warhammer 40,000: Space Marine 2",
    "Warhammer 40,000: Darktide",
    "Divinity: Original Sin 2",
    "Divinity: Original Sin",
    "Pillars of Eternity II: Deadfire",
    "Pillars of Eternity",
    "Pathfinder: Wrath of the Righteous",
    "Pathfinder: Kingmaker",
    "Wasteland 3",
    "Wasteland 2",
    "Baldur's Gate 2",
    "Baldur's Gate",
    "Planescape: Torment",
    "Icewind Dale",
    "Icewind Dale II",
    "Neverwinter Nights",
    "Neverwinter Nights 2",
    "GreedFall",
    "GreedFall 2",
    "ELEX",
    "ELEX 2",
    "Risen 3",
    "Risen 2",
    "Risen",
    "Gothic 3",
    "Gothic II",
    "Gothic",
    "Mount & Blade II: Bannerlord",
    "Mount & Blade: Warband",
    "Mount & Blade",
    "Dragon's Dogma 2",
    "Dragon's Dogma: Dark Arisen",
    "Dragon's Dogma",
    "Monster Hunter: World",
    "Monster Hunter Rise",
    "Tales of Arise",
    "Tales of Berseria",
    "Tales of Vesperia: Definitive Edition",
    "Tales of Symphonia",
    "Persona 5 Royal",
    "Persona 4 Golden",
    "Persona 3 Reload",
    "Persona 5 Strikers",
    "Shin Megami Tensei V: Vengeance",
    "Yakuza: Like a Dragon",
    "Like a Dragon: Infinite Wealth",
    "Like a Dragon Gaiden: The Man Who Erased His Name",
    "Yakuza 0",
    "Yakuza Kiwami",
    "Yakuza Kiwami 2",
    "Yakuza 3 Remastered",
    "Yakuza 4 Remastered",
    "Yakuza 5 Remastered",
    "Yakuza 6: The Song of Life",
    "Judgment",
    "Lost Judgment",
    "NieR:Automata",
    "NieR Replicant ver.1.22474487139",
    "Octopath Traveler II",
    "Octopath Traveler",
    "Triangle Strategy",
    "Dragon Quest XI S",
    "Ni no Kuni II: Revenant Kingdom",
    "Ni no Kuni: Wrath of the White Witch",
    "Kingdom Hearts III",
    "Kingdom Hearts HD 1.5+2.5 ReMIX",
    "Minecraft Java",
    "Minecraft Bedrock",
    "Terraria",
    "Stardew Valley",
    "Palworld",
    "Valheim",
    "ARK: Survival Ascended",
    "ARK: Survival Evolved",
    "7 Days to Die",
    "Project Zomboid",
    "Don't Starve Together",
    "Don't Starve",
    "Raft",
    "The Forest",
    "Sons of the Forest",
    "Green Hell",
    "Grounded",
    "Subnautica",
    "Subnautica: Below Zero",
    "No Man's Sky",
    "Enshrouded",
    "Core Keeper",
    "Starbound",
    "Factorio",
    "Satisfactory",
    "RimWorld",
    "Oxygen Not Included",
    "Kenshi",
    "Dwarf Fortress",
    "Astroneer",
    "Space Engineers",
    "Empyrion - Galactic Survival",
    "Conan Exiles",
    "Smalland: Survive the Wilds",
    "Icarus",
    "The Long Dark",
    "The Planet Crafter",
    "Stranded Deep",
    "Medieval Dynasty",
    "Bellwright",
    "Soulmask",
    "Nightingale",
    "Once Human",
    "Abiotic Factor",
    "Pacific Drive",
    "Lethal Company",
    "Content Warning",
    "Phasmophobia",
    "Demonologist",
    "Forewarned",
    "Devour",
    "GTFO",
    "Barotrauma",
    "Project Winter",
    "The Isle",
    "Path of Titans",
    "Beasts of Bermuda",
    "Marauders",
    "Voidtrain",
    "Sunkenland",
    "Dune: Awakening",
    "RuneScape: Dragonwilds",
    "Lightyear Frontier",
    "Forever Skies",
    "Wildmender",
    "Necesse",
    "Vintage Story",
    "Eco",
    "Wurm Unlimited",
    "Life is Feudal: MMO",
    "Cities: Skylines II",
    "Cities: Skylines",
    "SimCity",
    "SimCity 4 Deluxe",
    "The Sims 4",
    "The Sims 3",
    "The Sims 2",
    "Planet Zoo",
    "Planet Coaster 2",
    "Planet Coaster",
    "Zoo Tycoon",
    "RollerCoaster Tycoon 3",
    "Transport Fever 3",
    "Transport Fever 2",
    "Transport Fever",
    "American Truck Simulator",
    "Euro Truck Simulator 2",
    "Farming Simulator 25",
    "Farming Simulator 22",
    "Farming Simulator 19",
    "Microsoft Flight Simulator 2024",
    "Microsoft Flight Simulator",
    "X-Plane 12",
    "X-Plane 11",
    "BeamNG.drive",
    "Car Mechanic Simulator 2021",
    "Car Mechanic Simulator 2018",
    "PowerWash Simulator",
    "House Flipper 2",
    "House Flipper",
    "PC Building Simulator 2",
    "PC Building Simulator",
    "Two Point Hospital",
    "Two Point Campus",
    "Prison Architect",
    "Frostpunk 2",
    "Frostpunk",
    "Against the Storm",
    "Banished",
    "Anno 1800",
    "Anno 2205",
    "Anno 2070",
    "Anno 1404",
    "Age of Empires III: Definitive Edition",
    "Age of Empires II HD",
    "Age of Mythology",
    "Rise of Nations",
    "Rise of Nations: Extended Edition",
    "Stronghold Crusader HD",
    "Stronghold Crusader 2",
    "Stronghold",
    "Stronghold 2",
    "Stronghold Legends",
    "Civilization VI",
    "Civilization V",
    "Civilization IV",
    "Civilization III",
    "Civilization II",
    "Civilization: Beyond Earth",
    "Humankind",
    "Old World",
    "Endless Legend",
    "Endless Space 2",
    "Endless Space",
    "Stellaris",
    "Europa Universalis IV",
    "Europa Universalis III",
    "Hearts of Iron IV",
    "Hearts of Iron III",
    "Victoria 3",
    "Victoria II",
    "Crusader Kings III",
    "Crusader Kings II",
    "Total War: Rome Remastered",
    "Total War: Attila",
    "Total War: Napoleon",
    "Total War: Empire",
    "Total War: Medieval II",
    "Total War: Rome",
    "Total War: Troy",
    "Total War: Pharaoh",
    "Company of Heroes",
    "Warcraft III",
    "Age of Wonders 4",
    "Age of Wonders: Planetfall",
    "Age of Wonders III",
    "XCOM 2",
    "XCOM: Enemy Unknown",
    "XCOM: Enemy Within",
    "Phoenix Point",
    "Battletech",
    "MechWarrior 5: Mercenaries",
    "MechWarrior Online",
    "Surviving Mars",
    "Surviving the Aftermath",
    "Workers & Resources: Soviet Republic",
    "Dyson Sphere Program",
    "Captain of Industry",
    "Timberborn",
    "Manor Lords",
    "Foundation",
    "Farthest Frontier",
    "Songs of Syx",
    "Terra Invicta",
    "Ixion",
    "EA SPORTS FC 27",
    "EA SPORTS FC 26",
    "EA SPORTS FC 25",
    "EA SPORTS FC 24",
    "FIFA 23",
    "FIFA 22",
    "FIFA 21",
    "FIFA 20",
    "eFootball",
    "eFootball 2025",
    "eFootball 2026",
    "Football Manager 26",
    "Football Manager 25",
    "Football Manager 24",
    "Football Manager 23",
    "Football Manager 22",
    "Madden NFL 26",
    "Madden NFL 25",
    "NBA 2K26",
    "NBA 2K25",
    "NBA 2K24",
    "WWE 2K26",
    "WWE 2K25",
    "WWE 2K24",
    "F1 26",
    "F1 25",
    "F1 24",
    "F1 23",
    "F1 22",
    "F1 2021",
    "F1 2020",
    "Forza Horizon 5",
    "Forza Horizon 4",
    "Forza Horizon 3",
    "Forza Motorsport",
    "Forza Motorsport 7",
    "Gran Turismo 7",
    "Assetto Corsa Competizione",
    "Assetto Corsa",
    "iRacing",
    "Automobilista 2",
    "Automobilista",
    "Project CARS 3",
    "Project CARS 2",
    "Project CARS",
    "DiRT Rally 2.0",
    "DiRT Rally",
    "DiRT 5",
    "DiRT 4",
    "GRID Legends",
    "GRID 2019",
    "GRID Autosport",
    "GRID 2",
    "GRID",
    "Need for Speed Unbound",
    "Need for Speed Heat",
    "Need for Speed Payback",
    "Need for Speed Rivals",
    "Need for Speed Most Wanted",
    "Need for Speed Carbon",
    "Need for Speed Underground 2",
    "Need for Speed Underground",
    "Need for Speed Hot Pursuit Remastered",
    "Need for Speed Hot Pursuit",
    "Burnout Paradise Remastered",
    "Wreckfest",
    "The Crew Motorfest",
    "The Crew 2",
    "The Crew",
    "SnowRunner",
    "MudRunner",
    "CarX Drift Racing Online",
    "CarX Street",
    "Trackmania",
    "TrackMania Nations Forever",
    "TrackMania 2020",
    "Descenders",
    "Riders Republic",
    "Steep",
    "Tony Hawk's Pro Skater 1 + 2",
    "Session: Skate Sim",
    "Skater XL",
    "Hot Wheels Unleashed 2",
    "Hot Wheels Unleashed",
    "MotoGP 25",
    "MotoGP 24",
    "MotoGP 23",
    "Ride 5",
    "Ride 4",
    "WRC 10",
    "EA Sports WRC",
    "WRC Generations",
    "Silent Hill 2",
    "Silent Hill 3",
    "Silent Hill 4: The Room",
    "Silent Hill: Homecoming",
    "Silent Hill: Downpour",
    "Amnesia: The Dark Descent",
    "Amnesia: Rebirth",
    "Amnesia: The Bunker",
    "Outlast",
    "Outlast 2",
    "The Outlast Trials",
    "Alien: Isolation",
    "SOMA",
    "Layers of Fear",
    "Layers of Fear 2",
    "Little Nightmares",
    "Little Nightmares II",
    "Little Nightmares III",
    "Dead by Daylight",
    "Visage",
    "MADiSON",
    "The Mortuary Assistant",
    "Fobia - St. Dinfna Hotel",
    "Observer: System Redux",
    "Blair Witch",
    "The Medium",
    "Martha Is Dead",
    "Scorn",
    "SIGNALIS",
    "Darkwood",
    "Dying Light",
    "Dying Light 2 Stay Human",
    "Dead Island 2",
    "Dead Island Definitive Edition",
    "Dead Island Riptide",
    "Dead Island",
    "The Evil Within",
    "The Evil Within 2",
    "Back 4 Blood",
    "World War Z",
    "World War Z: Aftermath",
    "Killing Floor 2",
    "Killing Floor",
    "Left 4 Dead 2",
    "Left 4 Dead",
    "Hades II",
    "Hades",
    "Hollow Knight: Silksong",
    "Hollow Knight",
    "Celeste",
    "Dead Cells",
    "Cuphead",
    "Ori and the Will of the Wisps",
    "Ori and the Blind Forest",
    "Blasphemous 2",
    "Blasphemous",
    "Nine Sols",
    "Sea of Stars",
    "Chained Echoes",
    "Undertale",
    "Deltarune",
    "Slay the Spire 2",
    "Slay the Spire",
    "Balatro",
    "Vampire Survivors",
    "Risk of Rain 2",
    "Risk of Rain Returns",
    "Enter the Gungeon",
    "Exit the Gungeon",
    "Rogue Legacy 2",
    "Rogue Legacy",
    "FTL: Faster Than Light",
    "Into the Breach",
    "Papers, Please",
    "Return of the Obra Dinn",
    "Disco Elysium",
    "Outer Wilds",
    "What Remains of Edith Finch",
    "Firewatch",
    "Inside",
    "Limbo",
    "Gris",
    "Journey",
    "Abzu",
    "Stray",
    "Dave the Diver",
    "Dredge",
    "Cult of the Lamb",
    "Animal Well",
    "A Short Hike",
    "The Stanley Parable: Ultra Deluxe",
    "The Stanley Parable",
    "Portal 2",
    "Portal",
    "Half-Life: Alyx",
    "Half-Life 2",
    "Half-Life",
    "Black Mesa",
    "Unturned",
    "Among Us",
    "Fall Guys",
    "Human: Fall Flat",
    "Gang Beasts",
    "Goat Simulator 3",
    "Goat Simulator",
    "Totally Accurate Battle Simulator",
    "Totally Accurate Battlegrounds",
    "Teardown",
    "Besiege",
    "Poly Bridge 2",
    "Kerbal Space Program",
    "Kerbal Space Program 2",
    "Universe Sandbox",
    "Supermarket Simulator",
    "Schedule I",
    "VRChat",
    "Geometry Dash",
    "Wallpaper Engine",
    "Half-Life 2: Episode One",
    "Half-Life 2: Episode Two",
    "Half-Life 2: Lost Coast",
    "Counter-Strike",
    "Counter-Strike: Condition Zero",
    "Counter-Strike: Source",
    "Counter-Strike: Global Offensive",
    "Quake",
    "Quake II",
    "Quake III Arena",
    "DOOM II",
    "Wolfenstein 3D",
    "Return to Castle Wolfenstein",
    "Wolfenstein: Enemy Territory",
    "Unreal Tournament",
    "Unreal Tournament 2004",
    "Unreal Tournament 3",
    "Serious Sam Classic: The First Encounter",
    "Serious Sam Classic: The Second Encounter",
    "Serious Sam 4",
    "Bully: Scholarship Edition",
    "Grand Theft Auto III",
    "Grand Theft Auto: Vice City",
    "Grand Theft Auto: San Andreas",
    "Prototype",
    "Prototype 2",
    "Saints Row (2022)",
    "Shadow of Mordor",
    "Shadow of War",
    "BioShock 2"
  ],
  "upgradeNames": [
    "Counter-Strike 2",
    "Valorant",
    "League of Legends",
    "Dota 2",
    "Overwatch 2",
    "Apex Legends",
    "PUBG: Battlegrounds",
    "Fortnite",
    "Call of Duty: Warzone",
    "Call of Duty: Modern Warfare III",
    "Call of Duty: Black Ops 6",
    "Call of Duty: Black Ops 7",
    "Call of Duty: Modern Warfare II",
    "Call of Duty: Vanguard",
    "Call of Duty: Black Ops Cold War",
    "Call of Duty: Black Ops III",
    "Battlefield 2042",
    "Battlefield 6",
    "Battlefield V",
    "Battlefield 1",
    "Battlefield 4",
    "Battlefield 3",
    "Tom Clancy's Rainbow Six Siege",
    "Rainbow Six Extraction",
    "The Finals",
    "XDefiant",
    "Delta Force",
    "Arena Breakout: Infinite",
    "The Division 2",
    "Destiny 2",
    "Destiny",
    "Warframe",
    "Team Fortress 2",
    "Paladins",
    "Halo Infinite",
    "Halo: The Master Chief Collection",
    "Splitgate",
    "Splitgate 2",
    "Titanfall 2",
    "Marvel Rivals",
    "Deadlock",
    "Hunt: Showdown 1896",
    "Escape from Tarkov",
    "DayZ",
    "Rust",
    "ARK: Survival Ascended",
    "ARK: Survival Evolved",
    "7 Days to Die",
    "Conan Exiles",
    "Valheim",
    "Enshrouded",
    "Palworld",
    "V Rising",
    "Grounded",
    "Raft",
    "Sons of the Forest",
    "The Forest",
    "Project Zomboid",
    "Subnautica",
    "Subnautica: Below Zero",
    "No Man's Sky",
    "Astroneer",
    "Terraria",
    "Starbound",
    "Core Keeper",
    "Don't Starve Together",
    "Don't Starve",
    "Minecraft Java Edition",
    "Minecraft Dungeons",
    "Minecraft Legends",
    "Roblox",
    "Garry's Mod",
    "Unturned",
    "The Sims 4",
    "World of Warcraft",
    "Guild Wars 2",
    "Final Fantasy XIV Online",
    "Lost Ark",
    "New World: Aeternum",
    "Black Desert",
    "Throne and Liberty",
    "Path of Exile",
    "Path of Exile 2",
    "Diablo IV",
    "Diablo III",
    "Diablo II: Resurrected",
    "Last Epoch",
    "Grim Dawn",
    "Torchlight II",
    "Torchlight III",
    "Baldur's Gate 3",
    "Baldur's Gate 2",
    "Divinity: Original Sin 2",
    "Divinity: Original Sin",
    "Dragon Age: The Veilguard",
    "Dragon Age: Inquisition",
    "Dragon Age: Origins",
    "Dragon Age II",
    "Mass Effect Legendary Edition",
    "Mass Effect 3",
    "Mass Effect 2",
    "Mass Effect",
    "Starfield",
    "The Elder Scrolls V: Skyrim Special Edition",
    "The Elder Scrolls V: Skyrim",
    "The Elder Scrolls IV: Oblivion Remastered",
    "The Elder Scrolls IV: Oblivion",
    "The Elder Scrolls III: Morrowind",
    "Fallout 4",
    "Fallout: New Vegas",
    "Fallout 3",
    "Fallout 76",
    "Cyberpunk 2077",
    "Cyberpunk 2077: Phantom Liberty",
    "The Witcher 3: Wild Hunt",
    "The Witcher 2: Assassins of Kings",
    "The Witcher: Enhanced Edition",
    "Red Dead Redemption 2",
    "Red Dead Redemption",
    "Grand Theft Auto V Enhanced",
    "Grand Theft Auto V Legacy",
    "Grand Theft Auto IV",
    "Grand Theft Auto: San Andreas",
    "Grand Theft Auto: Vice City",
    "Grand Theft Auto III",
    "Grand Theft Auto Online",
    "Watch Dogs 2",
    "Watch Dogs",
    "Watch Dogs: Legion",
    "Mafia: Definitive Edition",
    "Mafia II: Definitive Edition",
    "Mafia III",
    "Sleeping Dogs: Definitive Edition",
    "Saints Row",
    "Saints Row: The Third Remastered",
    "Saints Row IV",
    "Just Cause 4",
    "Just Cause 3",
    "Just Cause 2",
    "Assassin's Creed Shadows",
    "Assassin's Creed Mirage",
    "Assassin's Creed Valhalla",
    "Assassin's Creed Odyssey",
    "Assassin's Creed Origins",
    "Assassin's Creed IV: Black Flag",
    "Assassin's Creed Unity",
    "Assassin's Creed Syndicate",
    "Assassin's Creed III Remastered",
    "Assassin's Creed II",
    "Assassin's Creed Brotherhood",
    "Assassin's Creed Revelations",
    "Far Cry 6",
    "Far Cry 5",
    "Far Cry New Dawn",
    "Far Cry 4",
    "Far Cry 3",
    "Far Cry 3: Blood Dragon",
    "Far Cry 2",
    "Dying Light 2 Stay Human",
    "Dying Light",
    "Dead Island 2",
    "Dead Island Definitive Edition",
    "Dead Island: Riptide",
    "Metro Exodus",
    "Metro Exodus Enhanced Edition",
    "Metro: Last Light Redux",
    "Metro 2033 Redux",
    "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    "S.T.A.L.K.E.R.: Call of Pripyat",
    "S.T.A.L.K.E.R.: Shadow of Chernobyl",
    "S.T.A.L.K.E.R.: Clear Sky",
    "Crysis Remastered",
    "Crysis 2 Remastered",
    "Crysis 3 Remastered",
    "DOOM Eternal",
    "DOOM",
    "DOOM (2016)",
    "DOOM 3",
    "Quake",
    "Quake II",
    "Quake III Arena",
    "Wolfenstein: The New Order",
    "Wolfenstein II: The New Colossus",
    "Wolfenstein: Youngblood",
    "RAGE 2",
    "RAGE",
    "Prey",
    "Dishonored 2",
    "Dishonored",
    "Deathloop",
    "Death Stranding Director's Cut",
    "Death Stranding",
    "Control Ultimate Edition",
    "Control",
    "Alan Wake 2",
    "Alan Wake Remastered",
    "Alan Wake",
    "Resident Evil 4",
    "Resident Evil 4 (2005)",
    "Resident Evil Village",
    "Resident Evil 7 Biohazard",
    "Resident Evil 6",
    "Resident Evil 5",
    "Resident Evil 3",
    "Resident Evil 2",
    "Resident Evil Revelations 2",
    "Resident Evil Revelations",
    "Resident Evil 0",
    "Resident Evil HD Remaster",
    "Silent Hill 2",
    "Silent Hill 3",
    "Silent Hill 4: The Room",
    "Dead Space",
    "Dead Space 2",
    "Dead Space 3",
    "Dead Space (2023)",
    "The Callisto Protocol",
    "Amnesia: The Bunker",
    "Amnesia: Rebirth",
    "Amnesia: The Dark Descent",
    "Outlast",
    "Outlast 2",
    "SOMA",
    "Alien: Isolation",
    "Little Nightmares",
    "Little Nightmares II",
    "The Evil Within",
    "The Evil Within 2",
    "Phasmophobia",
    "Lethal Company",
    "Content Warning",
    "Devour",
    "Visage",
    "The Medium",
    "Layers of Fear",
    "Until Dawn",
    "The Quarry",
    "Detroit: Become Human",
    "Heavy Rain",
    "Beyond: Two Souls",
    "Life is Strange",
    "Life is Strange: True Colors",
    "Life is Strange 2",
    "Life is Strange: Before the Storm",
    "The Walking Dead: The Telltale Definitive Series",
    "Tales from the Borderlands",
    "Borderlands 3",
    "Borderlands 2",
    "Borderlands: Game of the Year Enhanced",
    "Tiny Tina's Wonderlands",
    "The Outer Worlds",
    "The Outer Worlds 2",
    "Avowed",
    "Kingdom Come: Deliverance II",
    "Kingdom Come: Deliverance",
    "Mount & Blade II: Bannerlord",
    "Mount & Blade: Warband",
    "GreedFall",
    "GreedFall 2",
    "Elden Ring",
    "Elden Ring Nightreign",
    "Dark Souls Remastered",
    "Dark Souls II: Scholar of the First Sin",
    "Dark Souls III",
    "Sekiro: Shadows Die Twice",
    "Lies of P",
    "Nioh",
    "Nioh 2",
    "Wo Long: Fallen Dynasty",
    "Mortal Shell",
    "Lords of the Fallen",
    "Black Myth: Wukong",
    "Stellar Blade",
    "Final Fantasy VII Rebirth",
    "Final Fantasy VII Remake Intergrade",
    "Final Fantasy XVI",
    "Final Fantasy XV Windows Edition",
    "Final Fantasy XIII",
    "Final Fantasy X/X-2 HD Remaster",
    "Final Fantasy XII The Zodiac Age",
    "Dragon's Dogma 2",
    "Dragon's Dogma: Dark Arisen",
    "Monster Hunter Wilds",
    "Monster Hunter World",
    "Monster Hunter Rise",
    "Devil May Cry 5",
    "Devil May Cry 4 Special Edition",
    "Devil May Cry 3 Special Edition",
    "Ninja Gaiden 2 Black",
    "Ninja Gaiden: Master Collection",
    "Metal Gear Solid V: The Phantom Pain",
    "Metal Gear Solid V: Ground Zeroes",
    "Metal Gear Solid 3: Snake Eater",
    "Metal Gear Rising: Revengeance",
    "Yakuza: Like a Dragon",
    "Like a Dragon: Infinite Wealth",
    "Yakuza 0",
    "Yakuza Kiwami",
    "Yakuza Kiwami 2",
    "Yakuza 3 Remastered",
    "Yakuza 4 Remastered",
    "Yakuza 5 Remastered",
    "Yakuza 6: The Song of Life",
    "Judgment",
    "Lost Judgment",
    "Persona 5 Royal",
    "Persona 4 Golden",
    "Persona 3 Reload",
    "Shin Megami Tensei V: Vengeance",
    "Tales of Arise",
    "Tales of Berseria",
    "Tales of Zestiria",
    "NieR:Automata",
    "NieR Replicant ver.1.22474487139...",
    "Octopath Traveler",
    "Octopath Traveler II",
    "Sea of Stars",
    "Chained Echoes",
    "Star Wars Jedi: Survivor",
    "Star Wars Jedi: Fallen Order",
    "Star Wars Outlaws",
    "Star Wars Battlefront II",
    "Star Wars Squadrons",
    "Star Wars: Knights of the Old Republic",
    "Star Wars: Knights of the Old Republic II",
    "Star Wars: The Force Unleashed",
    "Star Wars: The Force Unleashed II",
    "Indiana Jones and the Great Circle",
    "Uncharted: Legacy of Thieves Collection",
    "Horizon Zero Dawn Complete Edition",
    "Horizon Forbidden West Complete Edition",
    "God of War",
    "God of War Ragnarök",
    "Marvel's Spider-Man Remastered",
    "Marvel's Spider-Man: Miles Morales",
    "Marvel's Spider-Man 2",
    "Days Gone",
    "Ghost of Tsushima DIRECTOR'S CUT",
    "Ghost of Tsushima",
    "The Last of Us Part I",
    "The Last of Us Part II Remastered",
    "Death Stranding 2: On the Beach",
    "Ratchet & Clank: Rift Apart",
    "Returnal",
    "Helldivers 2",
    "Helldivers",
    "Warhammer 40,000: Space Marine 2",
    "Warhammer 40,000: Darktide",
    "Vermintide 2",
    "Total War: WARHAMMER III",
    "Total War: WARHAMMER II",
    "Total War: Three Kingdoms",
    "Total War: Rome II",
    "Total War: Attila",
    "Total War: Shogun 2",
    "Civilization VI",
    "Civilization V",
    "Civilization VII",
    "Age of Empires IV",
    "Age of Empires II: Definitive Edition",
    "Age of Empires III: Definitive Edition",
    "Age of Mythology: Retold",
    "StarCraft II",
    "StarCraft Remastered",
    "Warcraft III: Reforged",
    "Company of Heroes 3",
    "Company of Heroes 2",
    "XCOM 2",
    "XCOM: Enemy Unknown",
    "XCOM: Chimera Squad",
    "Hearts of Iron IV",
    "Europa Universalis IV",
    "Crusader Kings III",
    "Stellaris",
    "RimWorld",
    "Factorio",
    "Satisfactory",
    "Dyson Sphere Program",
    "Cities: Skylines",
    "Cities: Skylines II",
    "Anno 1800",
    "Frostpunk",
    "Frostpunk 2",
    "Manor Lords",
    "Against the Storm",
    "Banished",
    "Planet Zoo",
    "Planet Coaster",
    "Planet Coaster 2",
    "Two Point Hospital",
    "Two Point Campus",
    "Kerbal Space Program",
    "Kerbal Space Program 2",
    "Microsoft Flight Simulator",
    "Microsoft Flight Simulator 2024",
    "X-Plane 12",
    "Euro Truck Simulator 2",
    "American Truck Simulator",
    "Farming Simulator 25",
    "Farming Simulator 22",
    "SnowRunner",
    "BeamNG.drive",
    "Assetto Corsa",
    "Assetto Corsa Competizione",
    "iRacing",
    "F1 25",
    "F1 24",
    "F1 23",
    "EA SPORTS FC 27",
    "EA SPORTS FC 26",
    "EA SPORTS FC 25",
    "FIFA 23",
    "eFootball",
    "NBA 2K26",
    "NBA 2K25",
    "WWE 2K26",
    "WWE 2K25",
    "NHL 26",
    "Madden NFL 26",
    "MLB The Show 26",
    "Forza Horizon 5",
    "Forza Motorsport",
    "Forza Horizon 4",
    "Need for Speed Unbound",
    "Need for Speed Heat",
    "Need for Speed Payback",
    "Need for Speed Rivals",
    "Need for Speed Hot Pursuit Remastered",
    "Need for Speed Most Wanted",
    "The Crew Motorfest",
    "The Crew 2",
    "The Crew",
    "DiRT Rally 2.0",
    "Dirt 5",
    "WRC 24",
    "MotoGP 25",
    "Ride 5",
    "Tekken 8",
    "Street Fighter 6",
    "Mortal Kombat 1",
    "Mortal Kombat 11",
    "Guilty Gear Strive",
    "Dragon Ball: Sparking! ZERO",
    "Dragon Ball FighterZ",
    "Naruto Shippuden: Ultimate Ninja Storm 4",
    "Injustice 2",
    "Soulcalibur VI",
    "Dead or Alive 6",
    "Brawlhalla",
    "Rocket League",
    "Trackmania",
    "Fall Guys",
    "Gang Beasts",
    "Human: Fall Flat",
    "Party Animals",
    "Among Us",
    "Goose Goose Duck",
    "Pummel Party",
    "Jackbox Party Pack 10",
    "Golf With Your Friends",
    "Tabletop Simulator",
    "Ultimate Chicken Horse",
    "It Takes Two",
    "A Way Out",
    "Split Fiction",
    "Portal 2",
    "Portal",
    "Left 4 Dead 2",
    "Left 4 Dead",
    "Back 4 Blood",
    "Deep Rock Galactic",
    "PAYDAY 3",
    "PAYDAY 2",
    "Killing Floor 2",
    "Killing Floor 3",
    "Ready or Not",
    "GTFO",
    "Insurgency: Sandstorm",
    "Squad",
    "Hell Let Loose",
    "BattleBit Remastered",
    "Enlisted",
    "Foxhole",
    "Arma 3",
    "Arma Reforger",
    "Day of Infamy",
    "Roboquest",
    "Risk of Rain 2",
    "Risk of Rain Returns",
    "Gunfire Reborn",
    "Deep Rock Galactic: Survivor",
    "Vampire Survivors",
    "Hades",
    "Hades II",
    "Dead Cells",
    "Hollow Knight",
    "Hollow Knight: Silksong",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "Cuphead",
    "Celeste",
    "Shovel Knight: Treasure Trove",
    "The Binding of Isaac: Rebirth",
    "Enter the Gungeon",
    "Slay the Spire",
    "Slay the Spire 2",
    "Balatro",
    "Inscryption",
    "Loop Hero",
    "Darkest Dungeon",
    "Darkest Dungeon II",
    "Rogue Legacy 2",
    "Noita",
    "Spelunky 2",
    "Stardew Valley",
    "Dave the Diver",
    "Dredge",
    "Cult of the Lamb",
    "Graveyard Keeper",
    "My Time at Sandrock",
    "My Time at Portia",
    "Coral Island",
    "Sun Haven",
    "Palia",
    "Disney Dreamlight Valley",
    "Hogwarts Legacy",
    "Avatar: Frontiers of Pandora",
    "Immortals Fenyx Rising",
    "Prince of Persia: The Lost Crown",
    "Prince of Persia: The Sands of Time",
    "Tomb Raider I-III Remastered",
    "Shadow of the Tomb Raider",
    "Rise of the Tomb Raider",
    "Tomb Raider (2013)",
    "Hitman World of Assassination",
    "Hitman 3",
    "Hitman 2",
    "Hitman (2016)",
    "Sniper Elite 5",
    "Sniper Elite 4",
    "Sniper Elite 3",
    "Ghost Recon Breakpoint",
    "Ghost Recon Wildlands",
    "Ghost Recon Future Soldier",
    "Splinter Cell Blacklist",
    "Splinter Cell Chaos Theory",
    "Mirror's Edge Catalyst",
    "Mirror's Edge",
    "Mad Max",
    "Middle-earth: Shadow of War",
    "Middle-earth: Shadow of Mordor",
    "Batman: Arkham Knight",
    "Batman: Arkham City",
    "Batman: Arkham Asylum",
    "Gotham Knights",
    "Suicide Squad: Kill the Justice League",
    "LEGO Star Wars: The Skywalker Saga",
    "LEGO Marvel Super Heroes 2",
    "LEGO Harry Potter Collection",
    "Sonic Frontiers",
    "Sonic Superstars",
    "Sonic Mania",
    "Crash Bandicoot 4: It's About Time",
    "Spyro Reignited Trilogy",
    "Rayman Legends",
    "Psychonauts 2",
    "Kena: Bridge of Spirits",
    "Stray",
    "Little Kitty, Big City",
    "A Plague Tale: Requiem",
    "A Plague Tale: Innocence",
    "Hellblade II: Senua's Saga",
    "Hellblade: Senua's Sacrifice",
    "Quantum Break",
    "Ryse: Son of Rome",
    "Atomic Heart",
    "Remnant II",
    "Remnant: From the Ashes",
    "Outriders",
    "Anthem",
    "Mass Effect: Andromeda",
    "Biomutant",
    "ELEX II",
    "ELEX",
    "Wasteland 3",
    "Wasteland 2",
    "Pillars of Eternity II: Deadfire",
    "Pillars of Eternity",
    "Pathfinder: Wrath of the Righteous",
    "Pathfinder: Kingmaker",
    "Disco Elysium",
    "South of Midnight",
    "Clair Obscur: Expedition 33",
    "Metaphor: ReFantazio",
    "Like a Dragon Gaiden: The Man Who Erased His Name",
    "Hi-Fi RUSH",
    "Ghostrunner 2",
    "Ghostrunner",
    "Katana ZERO",
    "Hotline Miami 2: Wrong Number",
    "Hotline Miami",
    "DOOM: The Dark Ages",
    "Gears of War: E-Day",
    "Gears 5",
    "Gears of War 4",
    "Gears of War: Ultimate Edition",
    "Gears Tactics",
    "Killer Klowns from Outer Space: The Game",
    "The Texas Chain Saw Massacre",
    "Mortal Kombat X",
    "Tekken 7",
    "Street Fighter V",
    "Street Fighter IV",
    "Dead by Daylight",
    "The Outlast Trials"
  ],
  "fpsProfiles": [
    {
      "name": "Counter-Strike 2",
      "cat": "Competitive",
      "gpu": 0.34,
      "cpu": 0.78,
      "base": 430,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Valorant",
      "cat": "Competitive",
      "gpu": 0.25,
      "cpu": 0.82,
      "base": 520,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "League of Legends",
      "cat": "Competitive",
      "gpu": 0.22,
      "cpu": 0.78,
      "base": 500,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Dota 2",
      "cat": "Competitive",
      "gpu": 0.38,
      "cpu": 0.72,
      "base": 390,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Overwatch 2",
      "cat": "Competitive",
      "gpu": 0.4,
      "cpu": 0.64,
      "base": 290,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Rainbow Six Siege",
      "cat": "Competitive",
      "gpu": 0.42,
      "cpu": 0.72,
      "base": 300,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Apex Legends",
      "cat": "Competitive",
      "gpu": 0.56,
      "cpu": 0.58,
      "base": 205,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Fortnite",
      "cat": "Competitive",
      "gpu": 0.55,
      "cpu": 0.6,
      "base": 230,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "The Finals",
      "cat": "Competitive",
      "gpu": 0.68,
      "cpu": 0.58,
      "base": 150,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "PUBG: Battlegrounds",
      "cat": "Competitive",
      "gpu": 0.55,
      "cpu": 0.63,
      "base": 190,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Rocket League",
      "cat": "Competitive",
      "gpu": 0.22,
      "cpu": 0.55,
      "base": 420,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Deadlock",
      "cat": "Competitive",
      "gpu": 0.48,
      "cpu": 0.62,
      "base": 210,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Marvel Rivals",
      "cat": "Competitive",
      "gpu": 0.65,
      "cpu": 0.55,
      "base": 145,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Call of Duty: Warzone",
      "cat": "Competitive",
      "gpu": 0.67,
      "cpu": 0.68,
      "base": 150,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Call of Duty: Black Ops 6",
      "cat": "AAA",
      "gpu": 0.66,
      "cpu": 0.63,
      "base": 155,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Call of Duty: Black Ops 7",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.65,
      "base": 145,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Battlefield 2042",
      "cat": "AAA",
      "gpu": 0.65,
      "cpu": 0.66,
      "base": 145,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Battlefield 6",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.7,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Destiny 2",
      "cat": "AAA",
      "gpu": 0.58,
      "cpu": 0.61,
      "base": 175,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Halo Infinite",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.63,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Halo: The Master Chief Collection",
      "cat": "AAA",
      "gpu": 0.48,
      "cpu": 0.58,
      "base": 220,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Cyberpunk 2077",
      "cat": "AAA",
      "gpu": 0.86,
      "cpu": 0.56,
      "base": 112,
      "vram": 8,
      "rt": 1.45
    },
    {
      "name": "Cyberpunk 2077: Phantom Liberty",
      "cat": "AAA",
      "gpu": 0.9,
      "cpu": 0.58,
      "base": 96,
      "vram": 8,
      "rt": 1.55
    },
    {
      "name": "Alan Wake 2",
      "cat": "AAA",
      "gpu": 0.93,
      "cpu": 0.54,
      "base": 86,
      "vram": 10,
      "rt": 1.7
    },
    {
      "name": "Black Myth: Wukong",
      "cat": "AAA",
      "gpu": 0.9,
      "cpu": 0.53,
      "base": 95,
      "vram": 10,
      "rt": 1.55
    },
    {
      "name": "The Last of Us Part I",
      "cat": "AAA",
      "gpu": 0.82,
      "cpu": 0.61,
      "base": 112,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "The Last of Us Part II",
      "cat": "AAA",
      "gpu": 0.84,
      "cpu": 0.59,
      "base": 108,
      "vram": 10,
      "rt": 1.18
    },
    {
      "name": "Hogwarts Legacy",
      "cat": "AAA",
      "gpu": 0.77,
      "cpu": 0.58,
      "base": 118,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Starfield",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.78,
      "base": 118,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Red Dead Redemption 2",
      "cat": "Open World",
      "gpu": 0.76,
      "cpu": 0.65,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Grand Theft Auto V",
      "cat": "Open World",
      "gpu": 0.58,
      "cpu": 0.64,
      "base": 185,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Grand Theft Auto VI",
      "cat": "Open World",
      "gpu": 0.9,
      "cpu": 0.8,
      "base": 82,
      "vram": 10,
      "rt": 1.15
    },
    {
      "name": "The Witcher 3: Wild Hunt",
      "cat": "RPG",
      "gpu": 0.68,
      "cpu": 0.58,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "The Witcher 3 Next-Gen",
      "cat": "RPG",
      "gpu": 0.78,
      "cpu": 0.58,
      "base": 108,
      "vram": 8,
      "rt": 1.22
    },
    {
      "name": "Elden Ring",
      "cat": "RPG",
      "gpu": 0.62,
      "cpu": 0.66,
      "base": 135,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Elden Ring Nightreign",
      "cat": "RPG",
      "gpu": 0.68,
      "cpu": 0.69,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Baldur's Gate 3",
      "cat": "RPG",
      "gpu": 0.56,
      "cpu": 0.74,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Dragon's Dogma 2",
      "cat": "RPG",
      "gpu": 0.78,
      "cpu": 0.82,
      "base": 95,
      "vram": 8,
      "rt": 1.15
    },
    {
      "name": "Kingdom Come: Deliverance II",
      "cat": "RPG",
      "gpu": 0.76,
      "cpu": 0.75,
      "base": 98,
      "vram": 8,
      "rt": 1.12
    },
    {
      "name": "Avowed",
      "cat": "RPG",
      "gpu": 0.76,
      "cpu": 0.62,
      "base": 105,
      "vram": 8,
      "rt": 1.18
    },
    {
      "name": "Fable",
      "cat": "RPG",
      "gpu": 0.78,
      "cpu": 0.66,
      "base": 98,
      "vram": 8,
      "rt": 1.18
    },
    {
      "name": "Final Fantasy VII Rebirth",
      "cat": "RPG",
      "gpu": 0.76,
      "cpu": 0.62,
      "base": 105,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Final Fantasy XVI",
      "cat": "RPG",
      "gpu": 0.79,
      "cpu": 0.6,
      "base": 104,
      "vram": 8,
      "rt": 1.12
    },
    {
      "name": "Final Fantasy XIV",
      "cat": "RPG",
      "gpu": 0.54,
      "cpu": 0.68,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Path of Exile 2",
      "cat": "RPG",
      "gpu": 0.72,
      "cpu": 0.72,
      "base": 118,
      "vram": 8,
      "rt": 1.05
    },
    {
      "name": "Diablo IV",
      "cat": "RPG",
      "gpu": 0.6,
      "cpu": 0.63,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Monster Hunter: World",
      "cat": "RPG",
      "gpu": 0.64,
      "cpu": 0.62,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Monster Hunter Wilds",
      "cat": "RPG",
      "gpu": 0.83,
      "cpu": 0.75,
      "base": 88,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "Monster Hunter Stories 3",
      "cat": "RPG",
      "gpu": 0.62,
      "cpu": 0.61,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Dragon Age: The Veilguard",
      "cat": "RPG",
      "gpu": 0.72,
      "cpu": 0.61,
      "base": 115,
      "vram": 8,
      "rt": 1.08
    },
    {
      "name": "Assassin's Creed Shadows",
      "cat": "Open World",
      "gpu": 0.78,
      "cpu": 0.72,
      "base": 104,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Assassin's Creed Valhalla",
      "cat": "Open World",
      "gpu": 0.68,
      "cpu": 0.69,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Assassin's Creed Mirage",
      "cat": "Open World",
      "gpu": 0.58,
      "cpu": 0.65,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Assassin's Creed Odyssey",
      "cat": "Open World",
      "gpu": 0.66,
      "cpu": 0.66,
      "base": 130,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Assassin's Creed Origins",
      "cat": "Open World",
      "gpu": 0.63,
      "cpu": 0.65,
      "base": 135,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Assassin's Creed Black Flag Resynced",
      "cat": "Open World",
      "gpu": 0.66,
      "cpu": 0.63,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Avatar: Frontiers of Pandora",
      "cat": "AAA",
      "gpu": 0.86,
      "cpu": 0.55,
      "base": 92,
      "vram": 10,
      "rt": 1.25
    },
    {
      "name": "Star Wars Outlaws",
      "cat": "AAA",
      "gpu": 0.84,
      "cpu": 0.58,
      "base": 94,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "Indiana Jones and the Great Circle",
      "cat": "AAA",
      "gpu": 0.88,
      "cpu": 0.58,
      "base": 88,
      "vram": 10,
      "rt": 1.35
    },
    {
      "name": "Doom Eternal",
      "cat": "AAA",
      "gpu": 0.55,
      "cpu": 0.54,
      "base": 235,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "DOOM: The Dark Ages",
      "cat": "AAA",
      "gpu": 0.82,
      "cpu": 0.59,
      "base": 105,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "Resident Evil 4",
      "cat": "AAA",
      "gpu": 0.67,
      "cpu": 0.57,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Resident Evil Village",
      "cat": "AAA",
      "gpu": 0.59,
      "cpu": 0.55,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Resident Evil Requiem",
      "cat": "AAA",
      "gpu": 0.88,
      "cpu": 0.6,
      "base": 90,
      "vram": 10,
      "rt": 1.25
    },
    {
      "name": "Resident Evil 2",
      "cat": "AAA",
      "gpu": 0.54,
      "cpu": 0.53,
      "base": 190,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Resident Evil 3",
      "cat": "AAA",
      "gpu": 0.55,
      "cpu": 0.52,
      "base": 185,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Silent Hill 2",
      "cat": "AAA",
      "gpu": 0.84,
      "cpu": 0.57,
      "base": 90,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "Lies of P",
      "cat": "RPG",
      "gpu": 0.62,
      "cpu": 0.54,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Armored Core VI",
      "cat": "RPG",
      "gpu": 0.64,
      "cpu": 0.57,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Sekiro: Shadows Die Twice",
      "cat": "RPG",
      "gpu": 0.48,
      "cpu": 0.54,
      "base": 210,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Dark Souls III",
      "cat": "RPG",
      "gpu": 0.43,
      "cpu": 0.52,
      "base": 230,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Dark Souls Remastered",
      "cat": "RPG",
      "gpu": 0.32,
      "cpu": 0.5,
      "base": 300,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Horizon Forbidden West",
      "cat": "AAA",
      "gpu": 0.79,
      "cpu": 0.6,
      "base": 112,
      "vram": 8,
      "rt": 1.12
    },
    {
      "name": "Horizon Zero Dawn Remastered",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.57,
      "base": 125,
      "vram": 8,
      "rt": 1.08
    },
    {
      "name": "God of War",
      "cat": "AAA",
      "gpu": 0.69,
      "cpu": 0.59,
      "base": 128,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "God of War Ragnarök",
      "cat": "AAA",
      "gpu": 0.76,
      "cpu": 0.6,
      "base": 112,
      "vram": 8,
      "rt": 1.08
    },
    {
      "name": "Marvel's Spider-Man Remastered",
      "cat": "AAA",
      "gpu": 0.74,
      "cpu": 0.6,
      "base": 132,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Marvel's Spider-Man 2",
      "cat": "AAA",
      "gpu": 0.83,
      "cpu": 0.63,
      "base": 105,
      "vram": 10,
      "rt": 1.1
    },
    {
      "name": "Ghost of Tsushima Director's Cut",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.59,
      "base": 122,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Days Gone Remastered",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.58,
      "base": 128,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Death Stranding Director's Cut",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.58,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Death Stranding 2: On the Beach",
      "cat": "AAA",
      "gpu": 0.78,
      "cpu": 0.61,
      "base": 102,
      "vram": 10,
      "rt": 1.1
    },
    {
      "name": "Uncharted: Legacy of Thieves",
      "cat": "AAA",
      "gpu": 0.69,
      "cpu": 0.59,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Ratchet & Clank: Rift Apart",
      "cat": "AAA",
      "gpu": 0.78,
      "cpu": 0.57,
      "base": 112,
      "vram": 8,
      "rt": 1.12
    },
    {
      "name": "Returnal",
      "cat": "AAA",
      "gpu": 0.81,
      "cpu": 0.61,
      "base": 102,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Control",
      "cat": "AAA",
      "gpu": 0.74,
      "cpu": 0.55,
      "base": 120,
      "vram": 8,
      "rt": 1.35
    },
    {
      "name": "Control Ultimate Edition",
      "cat": "AAA",
      "gpu": 0.76,
      "cpu": 0.56,
      "base": 112,
      "vram": 8,
      "rt": 1.4
    },
    {
      "name": "Metro Exodus Enhanced Edition",
      "cat": "AAA",
      "gpu": 0.87,
      "cpu": 0.54,
      "base": 100,
      "vram": 8,
      "rt": 1.6
    },
    {
      "name": "Metro Awakening",
      "cat": "AAA",
      "gpu": 0.89,
      "cpu": 0.54,
      "base": 82,
      "vram": 10,
      "rt": 1.55
    },
    {
      "name": "Atomic Heart",
      "cat": "AAA",
      "gpu": 0.69,
      "cpu": 0.55,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "S.T.A.L.K.E.R. 2",
      "cat": "AAA",
      "gpu": 0.84,
      "cpu": 0.7,
      "base": 88,
      "vram": 10,
      "rt": 1.18
    },
    {
      "name": "The Outer Worlds 2",
      "cat": "RPG",
      "gpu": 0.8,
      "cpu": 0.62,
      "base": 95,
      "vram": 10,
      "rt": 1.15
    },
    {
      "name": "Mass Effect Legendary Edition",
      "cat": "RPG",
      "gpu": 0.5,
      "cpu": 0.57,
      "base": 185,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Dragon Age: Inquisition",
      "cat": "RPG",
      "gpu": 0.57,
      "cpu": 0.59,
      "base": 160,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Banishers: Ghosts of New Eden",
      "cat": "RPG",
      "gpu": 0.72,
      "cpu": 0.59,
      "base": 110,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "GreedFall 2",
      "cat": "RPG",
      "gpu": 0.64,
      "cpu": 0.68,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Black Desert",
      "cat": "RPG",
      "gpu": 0.65,
      "cpu": 0.72,
      "base": 135,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Throne and Liberty",
      "cat": "RPG",
      "gpu": 0.7,
      "cpu": 0.7,
      "base": 115,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Lost Ark",
      "cat": "RPG",
      "gpu": 0.54,
      "cpu": 0.65,
      "base": 175,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "New World: Aeternum",
      "cat": "RPG",
      "gpu": 0.67,
      "cpu": 0.72,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "World of Warcraft",
      "cat": "RPG",
      "gpu": 0.52,
      "cpu": 0.76,
      "base": 185,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Guild Wars 2",
      "cat": "RPG",
      "gpu": 0.48,
      "cpu": 0.76,
      "base": 175,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "The Elder Scrolls Online",
      "cat": "RPG",
      "gpu": 0.5,
      "cpu": 0.7,
      "base": 180,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Forza Horizon 5",
      "cat": "AAA",
      "gpu": 0.66,
      "cpu": 0.59,
      "base": 155,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Forza Motorsport",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.66,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "F1 24",
      "cat": "AAA",
      "gpu": 0.59,
      "cpu": 0.6,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "F1 25",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.62,
      "base": 150,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Farming Simulator 25",
      "cat": "Simulation",
      "gpu": 0.58,
      "cpu": 0.66,
      "base": 135,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Microsoft Flight Simulator",
      "cat": "Simulation",
      "gpu": 0.66,
      "cpu": 0.86,
      "base": 95,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Microsoft Flight Simulator 2024",
      "cat": "Simulation",
      "gpu": 0.72,
      "cpu": 0.9,
      "base": 78,
      "vram": 10,
      "rt": 1.05
    },
    {
      "name": "Cities: Skylines II",
      "cat": "Simulation",
      "gpu": 0.64,
      "cpu": 0.9,
      "base": 70,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Transport Fever 2",
      "cat": "Simulation",
      "gpu": 0.45,
      "cpu": 0.7,
      "base": 130,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Euro Truck Simulator 2",
      "cat": "Simulation",
      "gpu": 0.35,
      "cpu": 0.63,
      "base": 180,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "American Truck Simulator",
      "cat": "Simulation",
      "gpu": 0.37,
      "cpu": 0.64,
      "base": 170,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Rust",
      "cat": "Survival",
      "gpu": 0.67,
      "cpu": 0.75,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "DayZ",
      "cat": "Survival",
      "gpu": 0.56,
      "cpu": 0.73,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "ARK: Survival Evolved",
      "cat": "Survival",
      "gpu": 0.68,
      "cpu": 0.72,
      "base": 115,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "ARK: Survival Ascended",
      "cat": "Survival",
      "gpu": 0.88,
      "cpu": 0.74,
      "base": 78,
      "vram": 10,
      "rt": 1.18
    },
    {
      "name": "Valheim",
      "cat": "Survival",
      "gpu": 0.48,
      "cpu": 0.68,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Enshrouded",
      "cat": "Survival",
      "gpu": 0.69,
      "cpu": 0.67,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Sons of the Forest",
      "cat": "Survival",
      "gpu": 0.67,
      "cpu": 0.66,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "The Forest",
      "cat": "Survival",
      "gpu": 0.48,
      "cpu": 0.61,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Palworld",
      "cat": "Survival",
      "gpu": 0.62,
      "cpu": 0.72,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Dune: Awakening",
      "cat": "Survival",
      "gpu": 0.76,
      "cpu": 0.72,
      "base": 98,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Subnautica",
      "cat": "Survival",
      "gpu": 0.46,
      "cpu": 0.58,
      "base": 180,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Subnautica 2",
      "cat": "Survival",
      "gpu": 0.72,
      "cpu": 0.68,
      "base": 100,
      "vram": 8,
      "rt": 1.05
    },
    {
      "name": "Raft",
      "cat": "Survival",
      "gpu": 0.43,
      "cpu": 0.6,
      "base": 175,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Grounded",
      "cat": "Survival",
      "gpu": 0.48,
      "cpu": 0.61,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "7 Days to Die",
      "cat": "Survival",
      "gpu": 0.61,
      "cpu": 0.72,
      "base": 125,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "V Rising",
      "cat": "Survival",
      "gpu": 0.51,
      "cpu": 0.64,
      "base": 160,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Don't Starve Together",
      "cat": "Survival",
      "gpu": 0.25,
      "cpu": 0.5,
      "base": 300,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Helldivers 2",
      "cat": "AAA",
      "gpu": 0.73,
      "cpu": 0.75,
      "base": 105,
      "vram": 8,
      "rt": 1.08
    },
    {
      "name": "Warhammer 40,000: Space Marine 2",
      "cat": "AAA",
      "gpu": 0.83,
      "cpu": 0.79,
      "base": 92,
      "vram": 10,
      "rt": 1.1
    },
    {
      "name": "Warhammer 40,000: Darktide",
      "cat": "AAA",
      "gpu": 0.76,
      "cpu": 0.79,
      "base": 100,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Deep Rock Galactic",
      "cat": "AAA",
      "gpu": 0.48,
      "cpu": 0.6,
      "base": 190,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Ready or Not",
      "cat": "AAA",
      "gpu": 0.67,
      "cpu": 0.72,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Escape from Tarkov",
      "cat": "AAA",
      "gpu": 0.63,
      "cpu": 0.88,
      "base": 105,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Hunt: Showdown 1896",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.68,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Insurgency: Sandstorm",
      "cat": "AAA",
      "gpu": 0.55,
      "cpu": 0.65,
      "base": 160,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Squad",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.8,
      "base": 125,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "BattleBit Remastered",
      "cat": "Competitive",
      "gpu": 0.35,
      "cpu": 0.66,
      "base": 280,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Gray Zone Warfare",
      "cat": "AAA",
      "gpu": 0.82,
      "cpu": 0.78,
      "base": 75,
      "vram": 10,
      "rt": 1.15
    },
    {
      "name": "ARC Raiders",
      "cat": "AAA",
      "gpu": 0.78,
      "cpu": 0.7,
      "base": 100,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Marathon",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.67,
      "base": 125,
      "vram": 8,
      "rt": 1.08
    },
    {
      "name": "Minecraft Java",
      "cat": "Survival",
      "gpu": 0.35,
      "cpu": 0.86,
      "base": 270,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Minecraft Java + Shaders",
      "cat": "Survival",
      "gpu": 0.72,
      "cpu": 0.74,
      "base": 105,
      "vram": 8,
      "rt": 1.12
    },
    {
      "name": "Roblox",
      "cat": "Competitive",
      "gpu": 0.3,
      "cpu": 0.6,
      "base": 280,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Terraria",
      "cat": "Survival",
      "gpu": 0.18,
      "cpu": 0.45,
      "base": 500,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Stardew Valley",
      "cat": "RPG",
      "gpu": 0.12,
      "cpu": 0.35,
      "base": 500,
      "vram": 2,
      "rt": 1
    },
    {
      "name": "Hades",
      "cat": "RPG",
      "gpu": 0.25,
      "cpu": 0.42,
      "base": 300,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Hades II",
      "cat": "RPG",
      "gpu": 0.32,
      "cpu": 0.45,
      "base": 260,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Hollow Knight",
      "cat": "RPG",
      "gpu": 0.14,
      "cpu": 0.38,
      "base": 400,
      "vram": 2,
      "rt": 1
    },
    {
      "name": "Silksong",
      "cat": "RPG",
      "gpu": 0.16,
      "cpu": 0.4,
      "base": 360,
      "vram": 2,
      "rt": 1
    },
    {
      "name": "Dead Cells",
      "cat": "RPG",
      "gpu": 0.13,
      "cpu": 0.36,
      "base": 450,
      "vram": 2,
      "rt": 1
    },
    {
      "name": "Genshin Impact",
      "cat": "RPG",
      "gpu": 0.48,
      "cpu": 0.58,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Honkai: Star Rail",
      "cat": "RPG",
      "gpu": 0.52,
      "cpu": 0.55,
      "base": 140,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Zenless Zone Zero",
      "cat": "RPG",
      "gpu": 0.56,
      "cpu": 0.55,
      "base": 135,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Wuthering Waves",
      "cat": "RPG",
      "gpu": 0.58,
      "cpu": 0.58,
      "base": 125,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Tower of Fantasy",
      "cat": "RPG",
      "gpu": 0.5,
      "cpu": 0.56,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Baldur's Gate 3",
      "cat": "RPG",
      "gpu": 0.56,
      "cpu": 0.74,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Divinity: Original Sin 2",
      "cat": "RPG",
      "gpu": 0.38,
      "cpu": 0.62,
      "base": 220,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Persona 5 Royal",
      "cat": "RPG",
      "gpu": 0.36,
      "cpu": 0.5,
      "base": 250,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Persona 3 Reload",
      "cat": "RPG",
      "gpu": 0.48,
      "cpu": 0.53,
      "base": 190,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Metaphor: ReFantazio",
      "cat": "RPG",
      "gpu": 0.52,
      "cpu": 0.58,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Like a Dragon: Infinite Wealth",
      "cat": "RPG",
      "gpu": 0.55,
      "cpu": 0.61,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Yakuza: Like a Dragon",
      "cat": "RPG",
      "gpu": 0.47,
      "cpu": 0.58,
      "base": 180,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Star Wars Jedi: Survivor",
      "cat": "AAA",
      "gpu": 0.78,
      "cpu": 0.66,
      "base": 100,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Star Wars Jedi: Fallen Order",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.59,
      "base": 140,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Uncharted: Legacy of Thieves Collection",
      "cat": "AAA",
      "gpu": 0.69,
      "cpu": 0.59,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "A Plague Tale: Requiem",
      "cat": "AAA",
      "gpu": 0.82,
      "cpu": 0.58,
      "base": 95,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "A Plague Tale: Innocence",
      "cat": "AAA",
      "gpu": 0.61,
      "cpu": 0.55,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Kena: Bridge of Spirits",
      "cat": "AAA",
      "gpu": 0.56,
      "cpu": 0.52,
      "base": 160,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Stray",
      "cat": "AAA",
      "gpu": 0.57,
      "cpu": 0.52,
      "base": 170,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "The Callisto Protocol",
      "cat": "AAA",
      "gpu": 0.72,
      "cpu": 0.56,
      "base": 110,
      "vram": 8,
      "rt": 1.2
    },
    {
      "name": "Dead Space",
      "cat": "AAA",
      "gpu": 0.77,
      "cpu": 0.57,
      "base": 112,
      "vram": 8,
      "rt": 1.18
    },
    {
      "name": "Dead Space 2",
      "cat": "AAA",
      "gpu": 0.4,
      "cpu": 0.5,
      "base": 250,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Mortal Kombat 1",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.58,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Tekken 8",
      "cat": "AAA",
      "gpu": 0.68,
      "cpu": 0.58,
      "base": 135,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Street Fighter 6",
      "cat": "AAA",
      "gpu": 0.57,
      "cpu": 0.55,
      "base": 170,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "EA Sports FC 26",
      "cat": "AAA",
      "gpu": 0.43,
      "cpu": 0.56,
      "base": 220,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "FIFA 23",
      "cat": "AAA",
      "gpu": 0.4,
      "cpu": 0.54,
      "base": 240,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Marvel's Guardians of the Galaxy",
      "cat": "AAA",
      "gpu": 0.66,
      "cpu": 0.55,
      "base": 135,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "The Division 2",
      "cat": "AAA",
      "gpu": 0.62,
      "cpu": 0.66,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "The Division 2: Warlords",
      "cat": "AAA",
      "gpu": 0.64,
      "cpu": 0.67,
      "base": 145,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Far Cry 6",
      "cat": "Open World",
      "gpu": 0.67,
      "cpu": 0.62,
      "base": 140,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Far Cry 5",
      "cat": "Open World",
      "gpu": 0.56,
      "cpu": 0.58,
      "base": 175,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Watch Dogs: Legion",
      "cat": "Open World",
      "gpu": 0.73,
      "cpu": 0.66,
      "base": 115,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Watch Dogs 2",
      "cat": "Open World",
      "gpu": 0.6,
      "cpu": 0.62,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Deathloop",
      "cat": "AAA",
      "gpu": 0.68,
      "cpu": 0.62,
      "base": 130,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Prey",
      "cat": "AAA",
      "gpu": 0.48,
      "cpu": 0.54,
      "base": 200,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Dishonored 2",
      "cat": "AAA",
      "gpu": 0.59,
      "cpu": 0.57,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Hogwarts Legacy",
      "cat": "AAA",
      "gpu": 0.77,
      "cpu": 0.58,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Immortals of Aveum",
      "cat": "AAA",
      "gpu": 0.86,
      "cpu": 0.6,
      "base": 88,
      "vram": 10,
      "rt": 1.2
    },
    {
      "name": "Forspoken",
      "cat": "AAA",
      "gpu": 0.82,
      "cpu": 0.62,
      "base": 92,
      "vram": 10,
      "rt": 1.1
    },
    {
      "name": "Lords of the Fallen",
      "cat": "RPG",
      "gpu": 0.79,
      "cpu": 0.61,
      "base": 92,
      "vram": 10,
      "rt": 1.18
    },
    {
      "name": "Remnant II",
      "cat": "RPG",
      "gpu": 0.78,
      "cpu": 0.65,
      "base": 100,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Remnant: From the Ashes",
      "cat": "RPG",
      "gpu": 0.61,
      "cpu": 0.58,
      "base": 150,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "The First Descendant",
      "cat": "AAA",
      "gpu": 0.79,
      "cpu": 0.68,
      "base": 105,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Once Human",
      "cat": "Survival",
      "gpu": 0.63,
      "cpu": 0.73,
      "base": 115,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Nightingale",
      "cat": "Survival",
      "gpu": 0.69,
      "cpu": 0.71,
      "base": 100,
      "vram": 8,
      "rt": 1.05
    },
    {
      "name": "Enshrouded",
      "cat": "Survival",
      "gpu": 0.69,
      "cpu": 0.67,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Sea of Thieves",
      "cat": "AAA",
      "gpu": 0.54,
      "cpu": 0.62,
      "base": 170,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "No Man's Sky",
      "cat": "AAA",
      "gpu": 0.65,
      "cpu": 0.67,
      "base": 135,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Star Citizen",
      "cat": "Simulation",
      "gpu": 0.72,
      "cpu": 0.88,
      "base": 85,
      "vram": 10,
      "rt": 1
    },
    {
      "name": "Elite Dangerous",
      "cat": "Simulation",
      "gpu": 0.52,
      "cpu": 0.7,
      "base": 170,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Kerbal Space Program",
      "cat": "Simulation",
      "gpu": 0.4,
      "cpu": 0.72,
      "base": 170,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Kerbal Space Program 2",
      "cat": "Simulation",
      "gpu": 0.6,
      "cpu": 0.8,
      "base": 95,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Planet Zoo",
      "cat": "Simulation",
      "gpu": 0.52,
      "cpu": 0.76,
      "base": 130,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Planet Coaster 2",
      "cat": "Simulation",
      "gpu": 0.56,
      "cpu": 0.78,
      "base": 115,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Age of Empires IV",
      "cat": "Strategy",
      "gpu": 0.42,
      "cpu": 0.7,
      "base": 185,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Civilization VI",
      "cat": "Strategy",
      "gpu": 0.34,
      "cpu": 0.73,
      "base": 230,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Civilization VII",
      "cat": "Strategy",
      "gpu": 0.48,
      "cpu": 0.76,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Total War: Warhammer III",
      "cat": "Strategy",
      "gpu": 0.63,
      "cpu": 0.86,
      "base": 105,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Total War: Three Kingdoms",
      "cat": "Strategy",
      "gpu": 0.57,
      "cpu": 0.83,
      "base": 120,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Crusader Kings III",
      "cat": "Strategy",
      "gpu": 0.28,
      "cpu": 0.82,
      "base": 260,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Europa Universalis IV",
      "cat": "Strategy",
      "gpu": 0.2,
      "cpu": 0.8,
      "base": 330,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Stellaris",
      "cat": "Strategy",
      "gpu": 0.25,
      "cpu": 0.86,
      "base": 280,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "RimWorld",
      "cat": "Strategy",
      "gpu": 0.15,
      "cpu": 0.74,
      "base": 380,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Factorio",
      "cat": "Strategy",
      "gpu": 0.13,
      "cpu": 0.82,
      "base": 450,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Satisfactory",
      "cat": "Simulation",
      "gpu": 0.62,
      "cpu": 0.76,
      "base": 135,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Dyson Sphere Program",
      "cat": "Simulation",
      "gpu": 0.42,
      "cpu": 0.76,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Manor Lords",
      "cat": "Strategy",
      "gpu": 0.68,
      "cpu": 0.82,
      "base": 105,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Frostpunk 2",
      "cat": "Strategy",
      "gpu": 0.72,
      "cpu": 0.84,
      "base": 92,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Anno 1800",
      "cat": "Strategy",
      "gpu": 0.58,
      "cpu": 0.84,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Age of Mythology: Retold",
      "cat": "Strategy",
      "gpu": 0.43,
      "cpu": 0.68,
      "base": 185,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Palworld",
      "cat": "Survival",
      "gpu": 0.62,
      "cpu": 0.72,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Lethal Company",
      "cat": "Survival",
      "gpu": 0.24,
      "cpu": 0.54,
      "base": 300,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Phasmophobia",
      "cat": "Survival",
      "gpu": 0.3,
      "cpu": 0.55,
      "base": 260,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Content Warning",
      "cat": "Survival",
      "gpu": 0.28,
      "cpu": 0.52,
      "base": 280,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Sons of the Forest",
      "cat": "Survival",
      "gpu": 0.67,
      "cpu": 0.66,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Project Zomboid",
      "cat": "Survival",
      "gpu": 0.24,
      "cpu": 0.76,
      "base": 300,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "The Long Dark",
      "cat": "Survival",
      "gpu": 0.35,
      "cpu": 0.56,
      "base": 220,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Path of Exile",
      "cat": "RPG",
      "gpu": 0.49,
      "cpu": 0.72,
      "base": 175,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Grim Dawn",
      "cat": "RPG",
      "gpu": 0.34,
      "cpu": 0.61,
      "base": 240,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Last Epoch",
      "cat": "RPG",
      "gpu": 0.46,
      "cpu": 0.68,
      "base": 185,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Torchlight II",
      "cat": "RPG",
      "gpu": 0.28,
      "cpu": 0.52,
      "base": 330,
      "vram": 3,
      "rt": 1
    },
    {
      "name": "Warframe",
      "cat": "RPG",
      "gpu": 0.49,
      "cpu": 0.62,
      "base": 220,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Warframe 1999",
      "cat": "RPG",
      "gpu": 0.59,
      "cpu": 0.65,
      "base": 175,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Resident Evil 7",
      "cat": "AAA",
      "gpu": 0.48,
      "cpu": 0.51,
      "base": 190,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Resident Evil Village",
      "cat": "AAA",
      "gpu": 0.59,
      "cpu": 0.55,
      "base": 165,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Devil May Cry 5",
      "cat": "AAA",
      "gpu": 0.53,
      "cpu": 0.53,
      "base": 205,
      "vram": 5,
      "rt": 1
    },
    {
      "name": "Final Fantasy XV",
      "cat": "RPG",
      "gpu": 0.67,
      "cpu": 0.58,
      "base": 125,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "NieR:Automata",
      "cat": "RPG",
      "gpu": 0.42,
      "cpu": 0.5,
      "base": 220,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "NieR Replicant",
      "cat": "RPG",
      "gpu": 0.39,
      "cpu": 0.49,
      "base": 230,
      "vram": 4,
      "rt": 1
    },
    {
      "name": "Valheim",
      "cat": "Survival",
      "gpu": 0.48,
      "cpu": 0.68,
      "base": 155,
      "vram": 6,
      "rt": 1
    },
    {
      "name": "Enshrouded",
      "cat": "Survival",
      "gpu": 0.69,
      "cpu": 0.67,
      "base": 118,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "Rust",
      "cat": "Survival",
      "gpu": 0.67,
      "cpu": 0.75,
      "base": 120,
      "vram": 8,
      "rt": 1
    },
    {
      "name": "ARK: Survival Ascended",
      "cat": "Survival",
      "gpu": 0.88,
      "cpu": 0.74,
      "base": 78,
      "vram": 10,
      "rt": 1.18
    },
    {
      "name": "Dune: Awakening",
      "cat": "Survival",
      "gpu": 0.76,
      "cpu": 0.72,
      "base": 98,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "ARC Raiders",
      "cat": "AAA",
      "gpu": 0.78,
      "cpu": 0.7,
      "base": 100,
      "vram": 8,
      "rt": 1.1
    },
    {
      "name": "Marathon",
      "cat": "AAA",
      "gpu": 0.7,
      "cpu": 0.67,
      "base": 125,
      "vram": 8,
      "rt": 1.08
    }
  ]
};
